### ISSUE TITLE
mobile device

### ISSUE THREAD

**Issue by VoroshilovMax** [Adfero/jScrollability#3]
Hi everyone! 
How I can turn on scroll effect in mobile devices? Do you can help me?

**Comment by Samurai016** [comment]
Since the plugin use the `top` CSS property, I simply force the `top` property on desktop using media queries.
The plugin will continue to calculate the `top` but it will be overridden by your class.
```css
@media screen and (max-width: 568px) {
    .element {
        position: relative; //if you need it
        top: 0 !important; // or whatever you need
    }
}
```
